"""Add A/B testing tables and models

Revision ID: a0fc025ad089
Revises: c56ed7f4ab95
Create Date: 2025-08-29 11:16:58.365362

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a0fc025ad089"
down_revision = "c56ed7f4ab95"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("primary_metric", sa.String(), nullable=False),
        sa.Column("secondary_metrics", sa.JSON(), nullable=True),
        sa.Column("target_audience", sa.JSON(), nullable=True),
        sa.Column("traffic_allocation", sa.Float(), nullable=True),
        sa.Column("minimum_sample_size", sa.Integer(), nullable=True),
        sa.Column("confidence_level", sa.Float(), nullable=True),
        sa.Column("minimum_effect_size", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiments_experiment_id"),
        "experiments",
        ["experiment_id"],
        unique=True,
    )
    op.create_index(op.f("ix_experiments_id"), "experiments", ["id"], unique=False)
    op.create_table(
        "experiment_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("analysis_date", sa.DateTime(), nullable=True),
        sa.Column("confidence_level", sa.Float(), nullable=True),
        sa.Column("control_conversion_rate", sa.Float(), nullable=True),
        sa.Column("control_sample_size", sa.Integer(), nullable=True),
        sa.Column("control_conversions", sa.Integer(), nullable=True),
        sa.Column("treatment_conversion_rate", sa.Float(), nullable=True),
        sa.Column("treatment_sample_size", sa.Integer(), nullable=True),
        sa.Column("treatment_conversions", sa.Integer(), nullable=True),
        sa.Column("p_value", sa.Float(), nullable=True),
        sa.Column("z_statistic", sa.Float(), nullable=True),
        sa.Column("confidence_interval_lower", sa.Float(), nullable=True),
        sa.Column("confidence_interval_upper", sa.Float(), nullable=True),
        sa.Column("lift", sa.Float(), nullable=True),
        sa.Column("is_statistically_significant", sa.Boolean(), nullable=True),
        sa.Column("is_practically_significant", sa.Boolean(), nullable=True),
        sa.Column("recommended_action", sa.String(), nullable=True),
        sa.Column("recommendation_reason", sa.Text(), nullable=True),
        sa.Column("detailed_results", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_results_id"), "experiment_results", ["id"], unique=False
    )
    op.create_table(
        "experiment_variants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("variant_id", sa.String(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("variant_type", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("traffic_allocation", sa.Float(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_variants_id"), "experiment_variants", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_experiment_variants_variant_id"),
        "experiment_variants",
        ["variant_id"],
        unique=True,
    )
    op.create_table(
        "user_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("assignment_context", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["experiment_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_assignments_assignment_id"),
        "user_assignments",
        ["assignment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_assignments_id"), "user_assignments", ["id"], unique=False
    )
    op.create_table(
        "experiment_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("experiment_id", sa.Integer(), nullable=True),
        sa.Column("variant_id", sa.Integer(), nullable=True),
        sa.Column("assignment_id", sa.Integer(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("metric_name", sa.String(), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("page_url", sa.String(), nullable=True),
        sa.Column("user_agent", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["user_assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["experiments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["experiment_variants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experiment_events_event_id"),
        "experiment_events",
        ["event_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_experiment_events_id"), "experiment_events", ["id"], unique=False
    )
    op.drop_index("ix_notification_logs_user_id", table_name="notification_logs")
    op.drop_table("notification_logs")
    op.drop_index("ix_push_subscriptions_user_id", table_name="push_subscriptions")
    op.drop_table("push_subscriptions")
    op.add_column(
        "users", sa.Column("notification_preferences", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notification_preferences")
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("endpoint", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("p256dh_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("auth_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_used", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="push_subscriptions_pkey"),
    )
    op.create_index(
        "ix_push_subscriptions_user_id", "push_subscriptions", ["user_id"], unique=False
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "notification_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("delivered", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("clicked", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="notification_logs_pkey"),
    )
    op.create_index(
        "ix_notification_logs_user_id", "notification_logs", ["user_id"], unique=False
    )
    op.drop_index(op.f("ix_experiment_events_id"), table_name="experiment_events")
    op.drop_index(op.f("ix_experiment_events_event_id"), table_name="experiment_events")
    op.drop_table("experiment_events")
    op.drop_index(op.f("ix_user_assignments_id"), table_name="user_assignments")
    op.drop_index(
        op.f("ix_user_assignments_assignment_id"), table_name="user_assignments"
    )
    op.drop_table("user_assignments")
    op.drop_index(
        op.f("ix_experiment_variants_variant_id"), table_name="experiment_variants"
    )
    op.drop_index(op.f("ix_experiment_variants_id"), table_name="experiment_variants")
    op.drop_table("experiment_variants")
    op.drop_index(op.f("ix_experiment_results_id"), table_name="experiment_results")
    op.drop_table("experiment_results")
    op.drop_index(op.f("ix_experiments_id"), table_name="experiments")
    op.drop_index(op.f("ix_experiments_experiment_id"), table_name="experiments")
    op.drop_table("experiments")
    # ### end Alembic commands ###
