"""Add user activity tracking models with unique session_id

Revision ID: b3300a3ef02f
Revises: 791169cd0a5c
Create Date: 2025-09-24 17:27:18.608162

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b3300a3ef02f"
down_revision = "791169cd0a5c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("insight_date", sa.DateTime(), nullable=False),
        sa.Column("total_session_time", sa.Integer(), nullable=True),
        sa.Column("unique_connections_viewed", sa.Integer(), nullable=True),
        sa.Column("revelations_shared", sa.Integer(), nullable=True),
        sa.Column("revelations_read", sa.Integer(), nullable=True),
        sa.Column("messages_sent", sa.Integer(), nullable=True),
        sa.Column("average_interaction_time", sa.Float(), nullable=True),
        sa.Column("deep_engagement_count", sa.Integer(), nullable=True),
        sa.Column("quick_browse_count", sa.Integer(), nullable=True),
        sa.Column("compatibility_views", sa.Integer(), nullable=True),
        sa.Column("energy_interactions", sa.Integer(), nullable=True),
        sa.Column("celebration_triggers", sa.Integer(), nullable=True),
        sa.Column("most_active_hour", sa.Integer(), nullable=True),
        sa.Column("preferred_activity_contexts", sa.JSON(), nullable=True),
        sa.Column("activity_flow_patterns", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_activity_insights_id"), "activity_insights", ["id"], unique=False
    )
    op.create_table(
        "user_activity_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(), nullable=True),
        sa.Column("browser_info", sa.JSON(), nullable=True),
        sa.Column("screen_resolution", sa.String(), nullable=True),
        sa.Column("device_capabilities", sa.JSON(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("network_type", sa.String(), nullable=True),
        sa.Column("connection_quality", sa.String(), nullable=True),
        sa.Column("interactions_count", sa.Integer(), nullable=True),
        sa.Column("pages_visited", sa.Integer(), nullable=True),
        sa.Column("websocket_reconnects", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_activity_sessions_id"),
        "user_activity_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_activity_sessions_session_id"),
        "user_activity_sessions",
        ["session_id"],
        unique=True,
    )
    op.create_table(
        "presence_activity_summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("current_activity", sa.String(), nullable=True),
        sa.Column("current_context", sa.String(), nullable=True),
        sa.Column("activity_started_at", sa.DateTime(), nullable=True),
        sa.Column("recent_activities", sa.JSON(), nullable=True),
        sa.Column("interactions_last_hour", sa.Integer(), nullable=True),
        sa.Column("pages_visited_last_hour", sa.Integer(), nullable=True),
        sa.Column("active_connection_id", sa.Integer(), nullable=True),
        sa.Column("connection_activity_type", sa.String(), nullable=True),
        sa.Column("connection_activity_started", sa.DateTime(), nullable=True),
        sa.Column("typical_session_duration", sa.Integer(), nullable=True),
        sa.Column("most_active_times", sa.JSON(), nullable=True),
        sa.Column("preferred_activities", sa.JSON(), nullable=True),
        sa.Column("display_status", sa.String(), nullable=True),
        sa.Column("status_emoji", sa.String(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["active_connection_id"],
            ["soul_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_presence_activity_summary_id"),
        "presence_activity_summary",
        ["id"],
        unique=False,
    )
    op.create_table(
        "user_activity_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("activity_type", sa.String(), nullable=False),
        sa.Column("activity_context", sa.String(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("connection_id", sa.Integer(), nullable=True),
        sa.Column("revelation_day", sa.Integer(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=True),
        sa.Column("activity_data", sa.JSON(), nullable=True),
        sa.Column("interaction_intensity", sa.Float(), nullable=True),
        sa.Column("emotional_context", sa.String(), nullable=True),
        sa.Column("page_load_time", sa.Float(), nullable=True),
        sa.Column("interaction_delay", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["soul_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["user_activity_sessions.session_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_activity_log_id"), "user_activity_log", ["id"], unique=False
    )

    # Drop tables and indexes only if they exist (conditional drops)
    # Use raw SQL to check existence before dropping
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # Drop notification_logs table and index if exists
    if "notification_logs" in existing_tables:
        op.drop_index(
            op.f("ix_notification_logs_user_id"),
            table_name="notification_logs",
            if_exists=True,
        )
        op.drop_table("notification_logs")

    # Drop push_subscriptions table and index if exists
    if "push_subscriptions" in existing_tables:
        op.drop_index(
            op.f("ix_push_subscriptions_user_id"),
            table_name="push_subscriptions",
            if_exists=True,
        )
        op.drop_table("push_subscriptions")

    # Drop moderation_actions table and indexes if exists
    if "moderation_actions" in existing_tables:
        op.drop_index(
            op.f("ix_moderation_actions_action_type"),
            table_name="moderation_actions",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_moderation_actions_created_at"),
            table_name="moderation_actions",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_moderation_actions_id"),
            table_name="moderation_actions",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_moderation_actions_is_active"),
            table_name="moderation_actions",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_moderation_actions_moderator_id"),
            table_name="moderation_actions",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_moderation_actions_target_user_id"),
            table_name="moderation_actions",
            if_exists=True,
        )
        op.drop_table("moderation_actions")

    # Drop user_reports table and indexes if exists
    if "user_reports" in existing_tables:
        op.drop_index(
            op.f("ix_user_reports_category"), table_name="user_reports", if_exists=True
        )
        op.drop_index(
            op.f("ix_user_reports_created_at"),
            table_name="user_reports",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_user_reports_id"), table_name="user_reports", if_exists=True
        )
        op.drop_index(
            op.f("ix_user_reports_reported_user_id"),
            table_name="user_reports",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_user_reports_reporter_id"),
            table_name="user_reports",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_user_reports_status"), table_name="user_reports", if_exists=True
        )
        op.drop_table("user_reports")

    # Drop simple_photo_reveals table and index if exists
    if "simple_photo_reveals" in existing_tables:
        op.drop_index(
            op.f("ix_simple_photo_reveals_id"),
            table_name="simple_photo_reveals",
            if_exists=True,
        )
        op.drop_table("simple_photo_reveals")

    # Drop user_safety_profiles table and indexes if exists
    if "user_safety_profiles" in existing_tables:
        op.drop_index(
            op.f("ix_user_safety_profiles_id"),
            table_name="user_safety_profiles",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_user_safety_profiles_safety_status"),
            table_name="user_safety_profiles",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_user_safety_profiles_total_reports"),
            table_name="user_safety_profiles",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_user_safety_profiles_user_id"),
            table_name="user_safety_profiles",
            if_exists=True,
        )
        op.drop_table("user_safety_profiles")

    # Drop blocked_users table and indexes if exists
    if "blocked_users" in existing_tables:
        op.drop_index(
            op.f("ix_blocked_users_blocked_user_id"),
            table_name="blocked_users",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_blocked_users_blocker_id"),
            table_name="blocked_users",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_blocked_users_created_at"),
            table_name="blocked_users",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_blocked_users_id"), table_name="blocked_users", if_exists=True
        )
        op.drop_table("blocked_users")

    # Check if tables exist before attempting to alter them
    # These tables may have been dropped by earlier migrations
    if "behavioral_patterns" in existing_tables:
        op.add_column(
            "behavioral_patterns",
            sa.Column("pattern_name", sa.String(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("pattern_description", sa.Text(), nullable=True),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("pattern_strength", sa.Float(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("pattern_consistency", sa.Float(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("first_observed", sa.DateTime(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("last_confirmed", sa.DateTime(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("observation_count", sa.Integer(), nullable=True),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("seasonal_component", sa.JSON(), nullable=True),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("detection_model_id", sa.Integer(), nullable=True),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("detection_confidence", sa.Float(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("detection_method", sa.String(), nullable=False),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("business_impact", sa.String(), nullable=True),
        )
        op.add_column(
            "behavioral_patterns",
            sa.Column("actionable_insights", sa.JSON(), nullable=True),
        )
        op.alter_column(
            "behavioral_patterns",
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.alter_column(
            "behavioral_patterns",
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.create_foreign_key(
            None, "behavioral_patterns", "ml_models", ["detection_model_id"], ["id"]
        )
        op.drop_column("behavioral_patterns", "prediction_value")
        op.drop_column("behavioral_patterns", "frequency")
        op.drop_column("behavioral_patterns", "strength")
        op.drop_column("behavioral_patterns", "last_observed")

    if "compatibility_predictions" in existing_tables:
        op.add_column(
            "compatibility_predictions",
            sa.Column("user1_profile_id", sa.Integer(), nullable=False),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("user2_profile_id", sa.Integer(), nullable=False),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("overall_compatibility", sa.Float(), nullable=False),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("personality_compatibility", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("values_compatibility", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("interests_compatibility", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("communication_compatibility", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("lifestyle_compatibility", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("conversation_quality_prediction", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("long_term_potential", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("conflict_likelihood", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("growth_potential", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("compatibility_reasons", sa.JSON(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("potential_challenges", sa.JSON(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("conversation_starters", sa.JSON(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("model_id", sa.Integer(), nullable=False),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("prediction_version", sa.String(), nullable=False),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("user_feedback_score", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("prediction_accuracy", sa.Float(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("expires_at", sa.DateTime(), nullable=True),
        )
        op.add_column(
            "compatibility_predictions",
            sa.Column("last_validated_at", sa.DateTime(), nullable=True),
        )
        op.alter_column(
            "compatibility_predictions",
            "prediction_date",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.alter_column(
            "compatibility_predictions",
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.alter_column(
            "compatibility_predictions",
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.drop_constraint(
            op.f("compatibility_predictions_user1_id_fkey"),
            "compatibility_predictions",
            type_="foreignkey",
        )
        op.drop_constraint(
            op.f("compatibility_predictions_user2_id_fkey"),
            "compatibility_predictions",
            type_="foreignkey",
        )
        op.create_foreign_key(
            None, "compatibility_predictions", "ml_models", ["model_id"], ["id"]
        )
        op.create_foreign_key(
            None,
            "compatibility_predictions",
            "user_profiles",
            ["user1_profile_id"],
            ["id"],
        )
        op.create_foreign_key(
            None,
            "compatibility_predictions",
            "user_profiles",
            ["user2_profile_id"],
            ["id"],
        )
        op.drop_column("compatibility_predictions", "user2_id")
        op.drop_column("compatibility_predictions", "prediction_reasoning")
        op.drop_column("compatibility_predictions", "accuracy_score")
        op.drop_column("compatibility_predictions", "compatibility_breakdown")
        op.drop_column("compatibility_predictions", "user1_id")
        op.drop_column("compatibility_predictions", "compatibility_score")
        op.drop_column("compatibility_predictions", "model_version")

    if "ml_models" in existing_tables:
        op.add_column("ml_models", sa.Column("description", sa.Text(), nullable=True))
        op.add_column(
            "ml_models", sa.Column("architecture", sa.String(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("input_features", sa.JSON(), nullable=True)
        )
        op.add_column("ml_models", sa.Column("output_schema", sa.JSON(), nullable=True))
        op.add_column(
            "ml_models", sa.Column("hyperparameters", sa.JSON(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("training_status", sa.String(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("training_data_size", sa.Integer(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("validation_accuracy", sa.Float(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("test_accuracy", sa.Float(), nullable=True)
        )
        op.add_column(
            "ml_models",
            sa.Column("training_duration_minutes", sa.Integer(), nullable=True),
        )
        op.add_column(
            "ml_models", sa.Column("inference_time_ms", sa.Float(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("memory_usage_mb", sa.Float(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("cpu_usage_percent", sa.Float(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("deployment_date", sa.DateTime(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("model_file_path", sa.String(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("model_checksum", sa.String(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("parent_model_id", sa.Integer(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("training_config", sa.JSON(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("feature_importance", sa.JSON(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("prediction_count", sa.Integer(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("error_count", sa.Integer(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("last_prediction_at", sa.DateTime(), nullable=True)
        )
        op.add_column(
            "ml_models", sa.Column("drift_detection_score", sa.Float(), nullable=True)
        )
        op.alter_column(
            "ml_models",
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.alter_column(
            "ml_models",
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.create_foreign_key(
            None, "ml_models", "ml_models", ["parent_model_id"], ["id"]
        )
        op.drop_column("ml_models", "training_date")
        op.drop_column("ml_models", "parameters")
        op.drop_column("ml_models", "performance_metrics")

    if "model_predictions" in existing_tables:
        op.add_column(
            "model_predictions",
            sa.Column("input_data_hash", sa.String(), nullable=False),
        )
        op.add_column(
            "model_predictions", sa.Column("input_features", sa.JSON(), nullable=False)
        )
        op.add_column(
            "model_predictions",
            sa.Column("prediction_quality", sa.String(), nullable=True),
        )
        op.add_column(
            "model_predictions",
            sa.Column("uncertainty_estimate", sa.Float(), nullable=True),
        )
        op.add_column(
            "model_predictions",
            sa.Column("feature_importance", sa.JSON(), nullable=True),
        )
        op.add_column(
            "model_predictions",
            sa.Column("ground_truth_value", sa.JSON(), nullable=True),
        )
        op.add_column(
            "model_predictions",
            sa.Column("prediction_error", sa.Float(), nullable=True),
        )
        op.add_column(
            "model_predictions",
            sa.Column("user_feedback_score", sa.Float(), nullable=True),
        )
        op.add_column(
            "model_predictions", sa.Column("session_id", sa.String(), nullable=True)
        )
        op.add_column(
            "model_predictions", sa.Column("request_source", sa.String(), nullable=True)
        )
        op.alter_column(
            "model_predictions",
            "prediction_type",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        op.alter_column(
            "model_predictions",
            "confidence_score",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        op.alter_column(
            "model_predictions",
            "processing_time_ms",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            nullable=False,
        )
        op.alter_column(
            "model_predictions",
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.drop_column("model_predictions", "input_data")

    if "personalized_recommendations" in existing_tables:
        op.add_column(
            "personalized_recommendations",
            sa.Column("user_profile_id", sa.Integer(), nullable=False),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("recommendation_content", sa.JSON(), nullable=False),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("priority_score", sa.Float(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("context_data", sa.JSON(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("user_segment", sa.String(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("timing_relevance", sa.Float(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("model_id", sa.Integer(), nullable=False),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("generation_algorithm", sa.String(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("confidence_score", sa.Float(), nullable=False),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("shown_to_user", sa.Boolean(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("shown_at", sa.DateTime(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("user_action", sa.String(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("user_feedback", sa.String(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("effectiveness_score", sa.Float(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("is_active", sa.Boolean(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("invalidation_reason", sa.String(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("experiment_id", sa.String(), nullable=True),
        )
        op.add_column(
            "personalized_recommendations",
            sa.Column("variant", sa.String(), nullable=True),
        )
        op.alter_column(
            "personalized_recommendations",
            "recommendation_type",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        op.alter_column(
            "personalized_recommendations",
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.alter_column(
            "personalized_recommendations",
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.drop_constraint(
            op.f("personalized_recommendations_recommended_user_id_fkey"),
            "personalized_recommendations",
            type_="foreignkey",
        )
        op.drop_constraint(
            op.f("personalized_recommendations_user_id_fkey"),
            "personalized_recommendations",
            type_="foreignkey",
        )
        op.create_foreign_key(
            None,
            "personalized_recommendations",
            "user_profiles",
            ["user_profile_id"],
            ["id"],
        )
        op.create_foreign_key(
            None, "personalized_recommendations", "ml_models", ["model_id"], ["id"]
        )
        op.drop_column("personalized_recommendations", "recommendation_reasons")
        op.drop_column("personalized_recommendations", "predicted_success_rate")
        op.drop_column("personalized_recommendations", "recommended_user_id")
        op.drop_column("personalized_recommendations", "user_id")
        op.drop_column("personalized_recommendations", "generated_at")
        op.drop_column("personalized_recommendations", "user_feedback_score")
        op.drop_column("personalized_recommendations", "recommendation_score")
        op.drop_column("personalized_recommendations", "actual_compatibility")
        op.drop_column("personalized_recommendations", "was_acted_upon")

    if "user_profiles" in existing_tables:
        op.add_column(
            "user_profiles",
            sa.Column("emotional_intelligence", sa.Float(), nullable=True),
        )
        op.add_column(
            "user_profiles", sa.Column("attachment_style", sa.String(), nullable=True)
        )
        op.add_column(
            "user_profiles",
            sa.Column("love_language_primary", sa.String(), nullable=True),
        )
        op.add_column(
            "user_profiles",
            sa.Column("love_language_secondary", sa.String(), nullable=True),
        )
        op.add_column(
            "user_profiles",
            sa.Column("communication_style", sa.String(), nullable=True),
        )
        op.add_column(
            "user_profiles",
            sa.Column("conversation_depth_preference", sa.Float(), nullable=True),
        )
        op.add_column(
            "user_profiles",
            sa.Column("response_time_pattern", sa.JSON(), nullable=True),
        )
        op.add_column(
            "user_profiles", sa.Column("emoji_usage_pattern", sa.JSON(), nullable=True)
        )
        op.add_column(
            "user_profiles", sa.Column("activity_patterns", sa.JSON(), nullable=True)
        )
        op.add_column(
            "user_profiles", sa.Column("engagement_patterns", sa.JSON(), nullable=True)
        )
        op.add_column(
            "user_profiles", sa.Column("decision_patterns", sa.JSON(), nullable=True)
        )
        op.add_column(
            "user_profiles", sa.Column("data_quality_score", sa.Float(), nullable=True)
        )
        op.add_column(
            "user_profiles", sa.Column("learning_rate", sa.Float(), nullable=True)
        )
        op.add_column(
            "user_profiles",
            sa.Column("ai_update_frequency", sa.Integer(), nullable=True),
        )
        op.add_column(
            "user_profiles", sa.Column("manual_overrides", sa.JSON(), nullable=True)
        )
        op.add_column(
            "user_profiles",
            sa.Column("ai_profiling_consent", sa.Boolean(), nullable=True),
        )
        op.add_column(
            "user_profiles", sa.Column("data_sharing_level", sa.String(), nullable=True)
        )
        op.alter_column(
            "user_profiles",
            "created_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
        op.alter_column(
            "user_profiles",
            "updated_at",
            existing_type=postgresql.TIMESTAMP(),
            nullable=False,
        )
    op.add_column(
        "users", sa.Column("notification_preferences", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notification_preferences")
    op.alter_column(
        "user_profiles",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "user_profiles",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("user_profiles", "data_sharing_level")
    op.drop_column("user_profiles", "ai_profiling_consent")
    op.drop_column("user_profiles", "manual_overrides")
    op.drop_column("user_profiles", "ai_update_frequency")
    op.drop_column("user_profiles", "learning_rate")
    op.drop_column("user_profiles", "data_quality_score")
    op.drop_column("user_profiles", "decision_patterns")
    op.drop_column("user_profiles", "engagement_patterns")
    op.drop_column("user_profiles", "activity_patterns")
    op.drop_column("user_profiles", "emoji_usage_pattern")
    op.drop_column("user_profiles", "response_time_pattern")
    op.drop_column("user_profiles", "conversation_depth_preference")
    op.drop_column("user_profiles", "communication_style")
    op.drop_column("user_profiles", "love_language_secondary")
    op.drop_column("user_profiles", "love_language_primary")
    op.drop_column("user_profiles", "attachment_style")
    op.drop_column("user_profiles", "emotional_intelligence")
    op.add_column(
        "personalized_recommendations",
        sa.Column("was_acted_upon", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "actual_compatibility",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "recommendation_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "user_feedback_score", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "generated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "recommended_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "predicted_success_rate",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "personalized_recommendations",
        sa.Column(
            "recommendation_reasons",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "personalized_recommendations", type_="foreignkey")
    op.drop_constraint(None, "personalized_recommendations", type_="foreignkey")
    op.create_foreign_key(
        op.f("personalized_recommendations_user_id_fkey"),
        "personalized_recommendations",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("personalized_recommendations_recommended_user_id_fkey"),
        "personalized_recommendations",
        "users",
        ["recommended_user_id"],
        ["id"],
    )
    op.alter_column(
        "personalized_recommendations",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "personalized_recommendations",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "personalized_recommendations",
        "recommendation_type",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("personalized_recommendations", "variant")
    op.drop_column("personalized_recommendations", "experiment_id")
    op.drop_column("personalized_recommendations", "invalidation_reason")
    op.drop_column("personalized_recommendations", "is_active")
    op.drop_column("personalized_recommendations", "effectiveness_score")
    op.drop_column("personalized_recommendations", "user_feedback")
    op.drop_column("personalized_recommendations", "user_action")
    op.drop_column("personalized_recommendations", "shown_at")
    op.drop_column("personalized_recommendations", "shown_to_user")
    op.drop_column("personalized_recommendations", "confidence_score")
    op.drop_column("personalized_recommendations", "generation_algorithm")
    op.drop_column("personalized_recommendations", "model_id")
    op.drop_column("personalized_recommendations", "timing_relevance")
    op.drop_column("personalized_recommendations", "user_segment")
    op.drop_column("personalized_recommendations", "context_data")
    op.drop_column("personalized_recommendations", "priority_score")
    op.drop_column("personalized_recommendations", "recommendation_content")
    op.drop_column("personalized_recommendations", "user_profile_id")
    op.add_column(
        "model_predictions",
        sa.Column(
            "input_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "model_predictions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "model_predictions",
        "processing_time_ms",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "model_predictions",
        "confidence_score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "model_predictions",
        "prediction_type",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("model_predictions", "request_source")
    op.drop_column("model_predictions", "session_id")
    op.drop_column("model_predictions", "user_feedback_score")
    op.drop_column("model_predictions", "prediction_error")
    op.drop_column("model_predictions", "ground_truth_value")
    op.drop_column("model_predictions", "feature_importance")
    op.drop_column("model_predictions", "uncertainty_estimate")
    op.drop_column("model_predictions", "prediction_quality")
    op.drop_column("model_predictions", "input_features")
    op.drop_column("model_predictions", "input_data_hash")
    op.add_column(
        "ml_models",
        sa.Column(
            "performance_metrics",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ml_models",
        sa.Column(
            "parameters",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "ml_models",
        sa.Column(
            "training_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "ml_models", type_="foreignkey")
    op.alter_column(
        "ml_models", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "ml_models", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("ml_models", "drift_detection_score")
    op.drop_column("ml_models", "last_prediction_at")
    op.drop_column("ml_models", "error_count")
    op.drop_column("ml_models", "prediction_count")
    op.drop_column("ml_models", "feature_importance")
    op.drop_column("ml_models", "training_config")
    op.drop_column("ml_models", "parent_model_id")
    op.drop_column("ml_models", "model_checksum")
    op.drop_column("ml_models", "model_file_path")
    op.drop_column("ml_models", "deployment_date")
    op.drop_column("ml_models", "cpu_usage_percent")
    op.drop_column("ml_models", "memory_usage_mb")
    op.drop_column("ml_models", "inference_time_ms")
    op.drop_column("ml_models", "training_duration_minutes")
    op.drop_column("ml_models", "test_accuracy")
    op.drop_column("ml_models", "validation_accuracy")
    op.drop_column("ml_models", "training_data_size")
    op.drop_column("ml_models", "training_status")
    op.drop_column("ml_models", "hyperparameters")
    op.drop_column("ml_models", "output_schema")
    op.drop_column("ml_models", "input_features")
    op.drop_column("ml_models", "architecture")
    op.drop_column("ml_models", "description")
    op.add_column(
        "compatibility_predictions",
        sa.Column("model_version", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "compatibility_predictions",
        sa.Column(
            "compatibility_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "compatibility_predictions",
        sa.Column("user1_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "compatibility_predictions",
        sa.Column(
            "compatibility_breakdown",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "compatibility_predictions",
        sa.Column(
            "accuracy_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "compatibility_predictions",
        sa.Column(
            "prediction_reasoning", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "compatibility_predictions",
        sa.Column("user2_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "compatibility_predictions", type_="foreignkey")
    op.drop_constraint(None, "compatibility_predictions", type_="foreignkey")
    op.drop_constraint(None, "compatibility_predictions", type_="foreignkey")
    op.create_foreign_key(
        op.f("compatibility_predictions_user2_id_fkey"),
        "compatibility_predictions",
        "users",
        ["user2_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("compatibility_predictions_user1_id_fkey"),
        "compatibility_predictions",
        "users",
        ["user1_id"],
        ["id"],
    )
    op.alter_column(
        "compatibility_predictions",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "compatibility_predictions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "compatibility_predictions",
        "prediction_date",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("compatibility_predictions", "last_validated_at")
    op.drop_column("compatibility_predictions", "expires_at")
    op.drop_column("compatibility_predictions", "prediction_accuracy")
    op.drop_column("compatibility_predictions", "user_feedback_score")
    op.drop_column("compatibility_predictions", "prediction_version")
    op.drop_column("compatibility_predictions", "model_id")
    op.drop_column("compatibility_predictions", "conversation_starters")
    op.drop_column("compatibility_predictions", "potential_challenges")
    op.drop_column("compatibility_predictions", "compatibility_reasons")
    op.drop_column("compatibility_predictions", "growth_potential")
    op.drop_column("compatibility_predictions", "conflict_likelihood")
    op.drop_column("compatibility_predictions", "long_term_potential")
    op.drop_column("compatibility_predictions", "conversation_quality_prediction")
    op.drop_column("compatibility_predictions", "lifestyle_compatibility")
    op.drop_column("compatibility_predictions", "communication_compatibility")
    op.drop_column("compatibility_predictions", "interests_compatibility")
    op.drop_column("compatibility_predictions", "values_compatibility")
    op.drop_column("compatibility_predictions", "personality_compatibility")
    op.drop_column("compatibility_predictions", "overall_compatibility")
    op.drop_column("compatibility_predictions", "user2_profile_id")
    op.drop_column("compatibility_predictions", "user1_profile_id")
    op.add_column(
        "behavioral_patterns",
        sa.Column(
            "last_observed", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "behavioral_patterns",
        sa.Column(
            "strength",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "behavioral_patterns",
        sa.Column("frequency", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "behavioral_patterns",
        sa.Column(
            "prediction_value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "behavioral_patterns", type_="foreignkey")
    op.alter_column(
        "behavioral_patterns",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.alter_column(
        "behavioral_patterns",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        nullable=True,
    )
    op.drop_column("behavioral_patterns", "actionable_insights")
    op.drop_column("behavioral_patterns", "business_impact")
    op.drop_column("behavioral_patterns", "detection_method")
    op.drop_column("behavioral_patterns", "detection_confidence")
    op.drop_column("behavioral_patterns", "detection_model_id")
    op.drop_column("behavioral_patterns", "seasonal_component")
    op.drop_column("behavioral_patterns", "observation_count")
    op.drop_column("behavioral_patterns", "last_confirmed")
    op.drop_column("behavioral_patterns", "first_observed")
    op.drop_column("behavioral_patterns", "pattern_consistency")
    op.drop_column("behavioral_patterns", "pattern_strength")
    op.drop_column("behavioral_patterns", "pattern_description")
    op.drop_column("behavioral_patterns", "pattern_name")
    op.create_table(
        "blocked_users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("blocker_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("blocked_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("reason", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["blocked_user_id"],
            ["users.id"],
            name=op.f("blocked_users_blocked_user_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["blocker_id"], ["users.id"], name=op.f("blocked_users_blocker_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blocked_users_pkey")),
        sa.UniqueConstraint(
            "blocker_id",
            "blocked_user_id",
            name=op.f("unique_block_relationship"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_blocked_users_id"), "blocked_users", ["id"], unique=False)
    op.create_index(
        op.f("ix_blocked_users_created_at"),
        "blocked_users",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blocked_users_blocker_id"),
        "blocked_users",
        ["blocker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_blocked_users_blocked_user_id"),
        "blocked_users",
        ["blocked_user_id"],
        unique=False,
    )
    op.create_table(
        "user_safety_profiles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "safety_status",
            postgresql.ENUM(
                "clear",
                "active",
                "flagged",
                "restricted",
                "suspended",
                "banned",
                "under_review",
                name="safetystatus",
            ),
            server_default=sa.text("'active'::safetystatus"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("restriction_reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "restriction_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "restriction_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "total_reports",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_report_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "safety_score",
            sa.INTEGER(),
            server_default=sa.text("100"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_safety_profiles_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_safety_profiles_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("unique_user_safety_profile"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_user_safety_profiles_user_id"),
        "user_safety_profiles",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_safety_profiles_total_reports"),
        "user_safety_profiles",
        ["total_reports"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_safety_profiles_safety_status"),
        "user_safety_profiles",
        ["safety_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_safety_profiles_id"), "user_safety_profiles", ["id"], unique=False
    )
    op.create_table(
        "simple_photo_reveals",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("connection_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("photo_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("reveal_status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "revealed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["soul_connections.id"],
            name=op.f("simple_photo_reveals_connection_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("simple_photo_reveals_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("simple_photo_reveals_pkey")),
    )
    op.create_index(
        op.f("ix_simple_photo_reveals_id"), "simple_photo_reveals", ["id"], unique=False
    )
    op.create_table(
        "user_reports",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('user_reports_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("reporter_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "reported_user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category",
            postgresql.ENUM(
                "harassment",
                "fake_profile",
                "inappropriate_photos",
                "inappropriate_content",
                "spam",
                "scam",
                "violence_threats",
                "hate_speech",
                "underage",
                "impersonation",
                "safety_concern",
                "other",
                name="reportcategory",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("evidence_urls", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "pending",
                "in_review",
                "resolved",
                "dismissed",
                "escalated",
                name="reportstatus",
            ),
            server_default=sa.text("'pending'::reportstatus"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("admin_notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resolved_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("resolved_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["reported_user_id"],
            ["users.id"],
            name="user_reports_reported_user_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id"], ["users.id"], name="user_reports_reporter_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by"], ["users.id"], name="user_reports_resolved_by_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="user_reports_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_user_reports_status"), "user_reports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_user_reports_reporter_id"),
        "user_reports",
        ["reporter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_reports_reported_user_id"),
        "user_reports",
        ["reported_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_user_reports_id"), "user_reports", ["id"], unique=False)
    op.create_index(
        op.f("ix_user_reports_created_at"), "user_reports", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_user_reports_category"), "user_reports", ["category"], unique=False
    )
    op.create_table(
        "moderation_actions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("target_user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("moderator_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "action_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "related_report_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("duration_hours", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["moderator_id"],
            ["users.id"],
            name=op.f("moderation_actions_moderator_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["related_report_id"],
            ["user_reports.id"],
            name=op.f("moderation_actions_related_report_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("moderation_actions_target_user_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("moderation_actions_pkey")),
    )
    op.create_index(
        op.f("ix_moderation_actions_target_user_id"),
        "moderation_actions",
        ["target_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_actions_moderator_id"),
        "moderation_actions",
        ["moderator_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_actions_is_active"),
        "moderation_actions",
        ["is_active"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_actions_id"), "moderation_actions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_moderation_actions_created_at"),
        "moderation_actions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_moderation_actions_action_type"),
        "moderation_actions",
        ["action_type"],
        unique=False,
    )
    op.create_table(
        "push_subscriptions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("endpoint", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("p256dh_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("auth_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_used", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("push_subscriptions_pkey")),
    )
    op.create_index(
        op.f("ix_push_subscriptions_user_id"),
        "push_subscriptions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "notification_logs",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "notification_type",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("body", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "sent_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("delivered", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("clicked", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("notification_logs_pkey")),
    )
    op.create_index(
        op.f("ix_notification_logs_user_id"),
        "notification_logs",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_user_activity_log_id"), table_name="user_activity_log")
    op.drop_table("user_activity_log")
    op.drop_index(
        op.f("ix_presence_activity_summary_id"), table_name="presence_activity_summary"
    )
    op.drop_table("presence_activity_summary")
    op.drop_index(
        op.f("ix_user_activity_sessions_session_id"),
        table_name="user_activity_sessions",
    )
    op.drop_index(
        op.f("ix_user_activity_sessions_id"), table_name="user_activity_sessions"
    )
    op.drop_table("user_activity_sessions")
    op.drop_index(op.f("ix_activity_insights_id"), table_name="activity_insights")
    op.drop_table("activity_insights")
    # ### end Alembic commands ###
