"""Add AI-enhanced matching models and profiles for Phase 5

Revision ID: dbaac808d228
Revises: f72637188530
Create Date: 2025-08-08 19:21:20.823711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dbaac808d228'
down_revision = 'f72637188530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables in correct dependency order
    op.drop_index(op.f('ix_photo_moderation_logs_id'), table_name='photo_moderation_logs')
    op.drop_table('photo_moderation_logs')
    op.drop_index(op.f('ix_photo_reveal_permissions_id'), table_name='photo_reveal_permissions') 
    op.drop_table('photo_reveal_permissions')
    op.drop_index(op.f('ix_photo_reveal_events_id'), table_name='photo_reveal_events')
    op.drop_table('photo_reveal_events')
    op.drop_index(op.f('ix_photo_reveal_requests_id'), table_name='photo_reveal_requests')
    op.drop_table('photo_reveal_requests')
    op.drop_index(op.f('ix_photo_reveal_timelines_id'), table_name='photo_reveal_timelines')
    op.drop_table('photo_reveal_timelines')
    op.drop_index(op.f('ix_user_photos_id'), table_name='user_photos')
    op.drop_index(op.f('ix_user_photos_photo_uuid'), table_name='user_photos')
    op.drop_table('user_photos')
    
    # Create AI models
    op.create_table('user_profiles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('personality_vector', sa.JSON(), nullable=True),
        sa.Column('interests_vector', sa.JSON(), nullable=True),
        sa.Column('values_vector', sa.JSON(), nullable=True),
        sa.Column('communication_vector', sa.JSON(), nullable=True),
        sa.Column('openness_score', sa.Float(), nullable=True),
        sa.Column('conscientiousness_score', sa.Float(), nullable=True),
        sa.Column('extraversion_score', sa.Float(), nullable=True),
        sa.Column('agreeableness_score', sa.Float(), nullable=True),
        sa.Column('neuroticism_score', sa.Float(), nullable=True),
        sa.Column('ai_confidence_level', sa.Float(), nullable=True),
        sa.Column('profile_completeness_score', sa.Float(), nullable=True),
        sa.Column('last_updated_by_ai', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    
    op.create_table('ml_models',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_name', sa.String(), nullable=False),
        sa.Column('model_type', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('performance_metrics', sa.JSON(), nullable=True),
        sa.Column('training_date', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_models_id'), 'ml_models', ['id'], unique=False)
    
    op.create_table('compatibility_predictions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user1_id', sa.Integer(), nullable=False),
        sa.Column('user2_id', sa.Integer(), nullable=False),
        sa.Column('compatibility_score', sa.Float(), nullable=False),
        sa.Column('confidence_level', sa.Float(), nullable=False),
        sa.Column('compatibility_breakdown', sa.JSON(), nullable=True),
        sa.Column('prediction_reasoning', sa.Text(), nullable=True),
        sa.Column('model_version', sa.String(), nullable=True),
        sa.Column('prediction_date', sa.DateTime(), nullable=True),
        sa.Column('actual_outcome', sa.String(), nullable=True),
        sa.Column('accuracy_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compatibility_predictions_id'), 'compatibility_predictions', ['id'], unique=False)
    
    op.create_table('personalized_recommendations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('recommended_user_id', sa.Integer(), nullable=False),
        sa.Column('recommendation_score', sa.Float(), nullable=False),
        sa.Column('recommendation_reasons', sa.JSON(), nullable=True),
        sa.Column('predicted_success_rate', sa.Float(), nullable=True),
        sa.Column('recommendation_type', sa.String(), nullable=True),
        sa.Column('generated_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('was_acted_upon', sa.Boolean(), nullable=True),
        sa.Column('user_feedback_score', sa.Integer(), nullable=True),
        sa.Column('actual_compatibility', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['recommended_user_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personalized_recommendations_id'), 'personalized_recommendations', ['id'], unique=False)
    
    op.create_table('model_predictions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('model_id', sa.Integer(), nullable=False),
        sa.Column('input_data', sa.JSON(), nullable=False),
        sa.Column('prediction_output', sa.JSON(), nullable=False),
        sa.Column('confidence_score', sa.Float(), nullable=False),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('prediction_type', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_predictions_id'), 'model_predictions', ['id'], unique=False)
    
    op.create_table('behavioral_patterns',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('pattern_type', sa.String(), nullable=False),
        sa.Column('pattern_data', sa.JSON(), nullable=False),
        sa.Column('frequency', sa.Integer(), nullable=True),
        sa.Column('strength', sa.Float(), nullable=True),
        sa.Column('last_observed', sa.DateTime(), nullable=True),
        sa.Column('trend_direction', sa.String(), nullable=True),
        sa.Column('prediction_value', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavioral_patterns_id'), 'behavioral_patterns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_reveal_permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('viewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('privacy_level', postgresql.ENUM('COMPLETELY_HIDDEN', 'SILHOUETTE', 'HEAVILY_BLURRED', 'LIGHTLY_BLURRED', 'FULLY_REVEALED', name='photoprivacylevel'), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_view_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('granted_through_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('grant_method', postgresql.ENUM('TIMELINE_BASED', 'MANUAL_REQUEST', 'MUTUAL_AGREEMENT', name='photoconsenttype'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['soul_connections.id'], name=op.f('photo_reveal_permissions_connection_id_fkey')),
    sa.ForeignKeyConstraint(['granted_through_request_id'], ['photo_reveal_requests.id'], name=op.f('photo_reveal_permissions_granted_through_request_id_fkey')),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photos.id'], name=op.f('photo_reveal_permissions_photo_id_fkey')),
    sa.ForeignKeyConstraint(['photo_owner_id'], ['users.id'], name=op.f('photo_reveal_permissions_photo_owner_id_fkey')),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('photo_reveal_permissions_viewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_reveal_permissions_pkey'))
    )
    op.create_index(op.f('ix_photo_reveal_permissions_id'), 'photo_reveal_permissions', ['id'], unique=False)
    op.create_table('photo_reveal_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timeline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('revelation_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emotional_state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('connection_energy_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('days_since_connection', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revelations_completed_at_time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('event_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('system_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['soul_connections.id'], name=op.f('photo_reveal_events_connection_id_fkey')),
    sa.ForeignKeyConstraint(['timeline_id'], ['photo_reveal_timelines.id'], name=op.f('photo_reveal_events_timeline_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('photo_reveal_events_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_reveal_events_pkey'))
    )
    op.create_index(op.f('ix_photo_reveal_events_id'), 'photo_reveal_events', ['id'], unique=False)
    op.create_table('photo_reveal_timelines',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('photo_reveal_timelines_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('connection_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('revelation_cycle_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auto_reveal_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('early_reveal_allowed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('connection_started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('revelation_cycle_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photo_reveal_eligible_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('current_stage', postgresql.ENUM('HIDDEN', 'CONSENT_REQUESTED', 'MUTUAL_CONSENT', 'REVEALED', 'DECLINED', name='photorevealstage'), autoincrement=False, nullable=True),
    sa.Column('days_until_reveal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('revelations_completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_revelations_required', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user1_consent_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user2_consent_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mutual_consent_achieved', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('consent_achieved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('photos_revealed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('photo_reveal_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reveal_method', postgresql.ENUM('TIMELINE_BASED', 'MANUAL_REQUEST', 'MUTUAL_AGREEMENT', name='photoconsenttype'), autoincrement=False, nullable=True),
    sa.Column('allow_partial_reveal', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gradual_reveal_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['soul_connections.id'], name='photo_reveal_timelines_connection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='photo_reveal_timelines_pkey'),
    sa.UniqueConstraint('connection_id', name='photo_reveal_timelines_connection_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_photo_reveal_timelines_id'), 'photo_reveal_timelines', ['id'], unique=False)
    op.create_table('user_photos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_photos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_uuid', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('original_filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('upload_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_profile_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('privacy_level', postgresql.ENUM('COMPLETELY_HIDDEN', 'SILHOUETTE', 'HEAVILY_BLURRED', 'LIGHTLY_BLURRED', 'FULLY_REVEALED', name='photoprivacylevel'), autoincrement=False, nullable=True),
    sa.Column('encryption_key_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blur_versions_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('silhouette_generated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('processing_complete', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('moderation_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('moderation_flags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('manual_review_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_reveals', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_revealed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_photos_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_photos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_user_photos_photo_uuid'), 'user_photos', ['photo_uuid'], unique=True)
    op.create_index(op.f('ix_user_photos_id'), 'user_photos', ['id'], unique=False)
    op.create_table('photo_reveal_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timeline_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('photo_owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('request_type', postgresql.ENUM('TIMELINE_BASED', 'MANUAL_REQUEST', 'MUTUAL_AGREEMENT', name='photoconsenttype'), autoincrement=False, nullable=False),
    sa.Column('request_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emotional_context', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('responded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('response_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('decline_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('requested_privacy_level', postgresql.ENUM('COMPLETELY_HIDDEN', 'SILHOUETTE', 'HEAVILY_BLURRED', 'LIGHTLY_BLURRED', 'FULLY_REVEALED', name='photoprivacylevel'), autoincrement=False, nullable=True),
    sa.Column('granted_privacy_level', postgresql.ENUM('COMPLETELY_HIDDEN', 'SILHOUETTE', 'HEAVILY_BLURRED', 'LIGHTLY_BLURRED', 'FULLY_REVEALED', name='photoprivacylevel'), autoincrement=False, nullable=True),
    sa.Column('photo_viewed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('first_viewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('total_views', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('view_duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photos.id'], name=op.f('photo_reveal_requests_photo_id_fkey')),
    sa.ForeignKeyConstraint(['photo_owner_id'], ['users.id'], name=op.f('photo_reveal_requests_photo_owner_id_fkey')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('photo_reveal_requests_requester_id_fkey')),
    sa.ForeignKeyConstraint(['timeline_id'], ['photo_reveal_timelines.id'], name=op.f('photo_reveal_requests_timeline_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_reveal_requests_pkey'))
    )
    op.create_index(op.f('ix_photo_reveal_requests_id'), 'photo_reveal_requests', ['id'], unique=False)
    op.create_table('photo_moderation_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moderation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moderator_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('moderator_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('flags_detected', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('violation_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('action_taken', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('moderation_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('appeal_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('appeal_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_model_version', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['moderator_id'], ['users.id'], name=op.f('photo_moderation_logs_moderator_id_fkey')),
    sa.ForeignKeyConstraint(['photo_id'], ['user_photos.id'], name=op.f('photo_moderation_logs_photo_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('photo_moderation_logs_pkey'))
    )
    op.create_index(op.f('ix_photo_moderation_logs_id'), 'photo_moderation_logs', ['id'], unique=False)
    # ### end Alembic commands ###

