"""Add photo reveal system models

Revision ID: f72637188530
Revises: d72d84e70503
Create Date: 2025-08-08 16:01:38.754973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f72637188530'
down_revision = 'd72d84e70503'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

