# Loki Configuration for Dinner First Dating Platform
# Optimized for SRE observability and log aggregation

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://alertmanager:9093

# Configure ingestion limits for dating platform
limits_config:
  # General limits
  ingestion_rate_mb: 50
  ingestion_burst_size_mb: 100
  max_concurrent_tail_requests: 20
  max_global_streams_per_user: 10000
  max_query_length: 12000h
  max_query_parallelism: 32
  max_streams_per_user: 0
  max_line_size: 256kb
  
  # Retention policies by stream
  retention_period: 30d
  
  # Query limits
  max_entries_limit_per_query: 5000
  max_query_series: 1000

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 30d

# Compactor for efficient storage
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

# Analytics for SRE insights
analytics:
  reporting_enabled: false

# Dating platform specific label extraction
chunk_store_config:
  max_look_back_period: 168h

query_scheduler:
  max_outstanding_requests_per_tenant: 100

frontend:
  max_outstanding_per_tenant: 100
  compress_responses: true
  log_queries_longer_than: 5s

frontend_worker:
  parallelism: 10

# Structured metadata support for rich log context
use_boltdb_shipper_as_backup: false

# Multi-tenancy disabled for single tenant deployment
distributor:
  ring:
    kvstore:
      store: inmemory